name: Build for Testing | Amplify Swift
on:
  workflow_call:
    inputs:
      identifier:
        required: true
        type: string
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - release

permissions:
  contents: read

concurrency:
  group: ${{ inputs.identifier || github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-for-testing-amplify-swift-iOS:
    runs-on: macos-13
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
        with:
          persist-credentials: false
      - name: Attempt to restore dependencies cache
        id: cache-packages
        timeout-minutes: 4
        continue-on-error: true
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/Library/Developer/Xcode/DerivedData/Amplify
          key: amplify-packages-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            amplify-packages-
      - name: Restore the build cache
        id: cache-build
        timeout-minutes: 4
        continue-on-error: true
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ github.workspace }}/Build
          key: amplify-iOS-latest-build-main
      - name: Build Amplify Swift for iOS
        uses: ./.github/composite_actions/run_xcodebuild
        with:
          scheme: Amplify-Package
          destination: 'platform=iOS Simulator,name=iPhone 14,OS=16.4'
          xcode_path: '/Applications/Xcode_14.3.app'
          disable_package_resolution: ${{ steps.cache-packages.outputs.cache-hit }}
          build_for_testing: true
          other_flags: '-derivedDataPath Build -clonedSourcePackagesDirPath ~/Library/Developer/Xcode/DerivedData/Amplify'
      - name: Enforce a cache update
        run: |
          CACHE_KEY="amplify-iOS-latest-build-$GITHUB_SHA"
          echo "STATE_CACHE_RESULT=${CACHE_KEY}" >> $GITHUB_ENV

  build-for-testing-amplify-swift-macOS:
    runs-on: macos-13
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
        with:
          persist-credentials: false
      - name: Attempt to restore dependencies cache
        id: cache-packages
        timeout-minutes: 4
        continue-on-error: true
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/Library/Developer/Xcode/DerivedData/Amplify
          key: amplify-packages-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            amplify-packages-
      - name: Restore the build cache
        id: cache-build
        timeout-minutes: 4
        continue-on-error: true
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ github.workspace }}/Build
          key: amplify-macOS-latest-build-main
      - name: Build Amplify Swift for macOS
        uses: ./.github/composite_actions/run_xcodebuild
        with:
          scheme: Amplify-Package
          destination: platform=macOS,arch=x86_64
          sdk: macosx
          xcode_path: '/Applications/Xcode_14.3.app'
          disable_package_resolution: ${{ steps.cache-packages.outputs.cache-hit }}
          build_for_testing: true
          other_flags: '-derivedDataPath Build -clonedSourcePackagesDirPath ~/Library/Developer/Xcode/DerivedData/Amplify'
      - name: Enforce a cache update
        run: |
          CACHE_KEY="amplify-macOS-latest-build-$GITHUB_SHA"
          echo "STATE_CACHE_RESULT=${CACHE_KEY}" >> $GITHUB_ENV

  build-for-testing-amplify-swift-tvOS:
    runs-on: macos-13
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
        with:
          persist-credentials: false
      - name: Attempt to restore dependencies cache
        timeout-minutes: 4
        id: cache-packages
        continue-on-error: true
        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/Library/Developer/Xcode/DerivedData/Amplify
          key: amplify-packages-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            amplify-packages-
      - name: Restore the build cache
        id: cache-build
        timeout-minutes: 4
        continue-on-error: true
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ github.workspace }}/Build
          key: amplify-tvOS-latest-build-main
      - name: Build Amplify Swift for tvOS
        uses: ./.github/composite_actions/run_xcodebuild
        with:
          scheme: Amplify-Package
          destination: platform=tvOS Simulator,name=Apple TV 4K (3rd generation),OS=16.4
          sdk: appletvsimulator
          xcode_path: '/Applications/Xcode_14.3.app'
          disable_package_resolution: ${{ steps.cache-packages.outputs.cache-hit }}
          build_for_testing: true
          other_flags: '-derivedDataPath Build -clonedSourcePackagesDirPath ~/Library/Developer/Xcode/DerivedData/Amplify'
      - name: Enforce a cache update
        run: |
          CACHE_KEY="amplify-tvOS-latest-build-$GITHUB_SHA"
          echo "STATE_CACHE_RESULT=${CACHE_KEY}" >> $GITHUB_ENV

  build-for-testing-amplify-swift-watchOS:
    runs-on: macos-13
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
        with:
          persist-credentials: false
      - name: Attempt to restore dependencies cache
        id: cache-packages
        timeout-minutes: 4
        continue-on-error: true
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/Library/Developer/Xcode/DerivedData/Amplify
          key: amplify-packages-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            amplify-packages-
      - name: Restore the build cache
        id: cache-build
        timeout-minutes: 4
        continue-on-error: true
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ github.workspace }}/Build
          key: amplify-watchOS-latest-build-main
      - name: Build Amplify Swift for watchOS
        uses: ./.github/composite_actions/run_xcodebuild
        with:
          scheme: Amplify-Package
          destination: platform=watchOS Simulator,name=Apple Watch Series 8 (45mm),OS=9.4
          sdk: watchsimulator
          xcode_path: '/Applications/Xcode_14.3.app'
          disable_package_resolution: ${{ steps.cache-packages.outputs.cache-hit }}
          build_for_testing: true
          other_flags: '-derivedDataPath Build -clonedSourcePackagesDirPath ~/Library/Developer/Xcode/DerivedData/Amplify'
      - name: Enforce a cache update
        run: |
          CACHE_KEY="amplify-watchOS-latest-build-$GITHUB_SHA"
          echo "STATE_CACHE_RESULT=${CACHE_KEY}" >> $GITHUB_ENV
