name: Uploads the coverage report file to Codecov
on:
  workflow_call:
    inputs:      
      scheme:
        description: 'The name of the scheme whose coverage needs to be uploaded.'
        required: true
        type: string
      flags:
        description: 'What flags to include in the coverage report, separated by commas'
        required: false
        type: string
        default: 'tests'

permissions:
    contents: read

jobs:
  upload-coverage:
    name: ${{ inputs.scheme }} Coverage Report
    runs-on: macos-13
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3
        with:
          persist-credentials: false

      - name: Retrieve Coverage report
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a #v3.0.2
        with:
          name: ${{ inputs.scheme }}-Coverage-${{ github.sha }}
          path: ${{ github.workspace }}

      - name: Upload report to Codecov
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          flags: ${{ inputs.flags }}
          fail_ci_if_error: true